apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapp
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: myapptarget
  template:
    metadata:
      name: '{{name}}-myapp'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/burrsutter/doks-argocd.git
        targetRevision: main
        path: 'mystuff/overlays/{{name}}'
      destination:
        server: '{{server}}'
        namespace: mystuff